version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  petclinic:
    image: spring-petclinic:v3
    container_name: petclinic

    depends_on:
      mysql:
        condition: service_healthy

    restart: unless-stopped

    ports:
      - "8085:8085"

    environment:
      SPRING_PROFILES_ACTIVE: mysql

      MYSQL_URL: jdbc:mysql://mysql:3306/petclinic?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

      MYSQL_USER: petclinic
      MYSQL_PASS: petclinic

volumes:
  mysql-data: